### ISSUE TITLE
.ivy2 file

### ISSUE THREAD

**Issue by sgaseretto** [radek1st/BigDataRiver#1]
Hello, do you have an example file of what should the .ivy2 file contain? It isn't in the repo but it is listed in the volumes of spark in the docker-compose file

**Comment by radek1st** [comment]
You can safely remove the reference (or update to https://github.com/radek1st/BigDataRiver/commit/adf1dbe6ebfdd1a2096b12be735739fe41d7e989). I used it as a local cache to speed up dependency resolution.
