### ISSUE TITLE
Batch Layer and Master Data

### ISSUE THREAD

**Issue by sgaseretto** [radek1st/BigDataRiver#2]
First of all, I find your project really awesome! But I have this doubt, when testing the containers as a Lambda architecture, the Cassandra container can be seen as both the Serving Layer and Speed Layer, but which container performs as the Batch Layer where the Master Data is stored?

**Comment by radek1st** [comment]
Thanks mate. For this Lambda example, Spark Streaming is the Speed Layer and Spark Core is the Batch Layer. Cassandra is a Serving Layer for the web service.
